apiVersion: db.zernico.de/v1alpha1
kind: PostgreSQLUser
metadata:
  name: my-app
  namespace: myapp-staging
spec:
  postgresRef:
    name: postgresql-staging
    namespace: postgresql
  name: "myapp_staging"
  passwordSecretKeyRef:
    name: my-app-db
    key: password
  cleanupPolicy: Skip
